version: '3.9'

services:
  mongo:
    container_name: mongo420
    image: mongo:latest
    restart : always
    ports:
      - "27017:27017"

    networks:
      - shared-network
    volumes:
      - mongo_data:/data/db 

  api:
    container_name: estate-api
    restart : unless-stopped
    image: estate-api-prod:1.0.0
    build: 
      context : api
      target: development
      dockerfile: Dockerfile
    environment:
      - MONGO=mongodb://mongo420:27017/db
      - JWT_SECRET=6504802356
    ports:
      - "3000:3000"
    networks:
      - shared-network
    depends_on:
      - mongo
  
  client:
    container_name: estate-client
    restart : unless-stopped
    image: estate-client-prod:1.0.0
    build: 
      context : client
      target: production
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    networks:
      - shared-network
    depends_on:
      - api
  
networks:
  shared-network:

volumes:
  mongo_data:  
    
      


  

    
